#!/bin/bash

SEAFILE_INSTALL_DIR=/opt/seafile

if [[ ! -d "$SEAFILE_INSTALL_DIR/conf" ]]; then
    echo "Seafile configuration directory '$SEAFILE_INSTALL_DIR/conf' does not exist!"
    exit 1
fi

export SEAFILE_DEBUG=debug

SEAF_ARGS=(\
    -c "${SEAFILE_INSTALL_DIR}/ccnet"
	-F "${SEAFILE_INSTALL_DIR}/conf"
    -d "${SEAFILE_INSTALL_DIR}/seafile-data"
    # -l -
    -f  # foreground
)

cd "${SEAFILE_INSTALL_DIR}/seafile-server"
echo "Starting seaf-server..."
exec s6-envuidgid seafile /usr/local/bin/seaf-server "${SEAF_ARGS[@]}"

