#!/bin/bash

set -e

if [[ -z "$LANG" ]]; then
    echo "LANG is not set in ENV, set to en_US.UTF-8"
    export LANG='en_US.UTF-8'
fi
if [[ -z "$LC_ALL" ]]; then
    echo "LC_ALL is not set in ENV, set to en_US.UTF-8"
    export LC_ALL='en_US.UTF-8'
fi

SEAFILE_INSTALL_DIR=/opt/seafile
SEAFILE_SERVER_DIR=${SEAFILE_INSTALL_DIR}/seafile-server
SEAHUB_DIR=${SEAFILE_SERVER_DIR}/seahub
REAL_CONF_DIR=${SEAFILE_INSTALL_DIR}/conf
gunicorn=gunicorn

# export environment required by seahub
# Note: those var names are really messed up
export CCNET_CONF_DIR=${SEAFILE_INSTALL_DIR}/ccnet  # yep, they're swapped
export SEAFILE_CONF_DIR=${SEAFILE_INSTALL_DIR}/seafile-data
export SEAFILE_CENTRAL_CONF_DIR=${SEAFILE_INSTALL_DIR}/conf
export SEAFILE_RPC_PIPE_PATH="${SEAFILE_SERVER_DIR}/runtime"
export SEAHUB_LOG_DIR="${SEAFILE_SERVER_DIR}/seahub/"

export SEAFILE_UCI_DATA_DIR="${SEAFILE_DATA_DIR}/seahub-data"
export PYTHONPATH="${SEAHUB_DIR}:${SEAHUB_DIR}/thirdpart:$PYTHONPATH"

# create pids dir if not existing
s6-setuidgid seafile mkdir -p "/opt/seafile/pids"
cd "${SEAFILE_SERVER_DIR}/seahub/"

# make gunicorn run in foreground
echo "Running Seahub in gunicorn mode..."
sed -i 's/^daemon\s*=.*/daemon = False/' "${REAL_CONF_DIR}/gunicorn.conf.py"

exec s6-setuidgid seafile "$gunicorn" \
    -c "${REAL_CONF_DIR}/gunicorn.conf.py" \
    --error-logfile - --log-file - \
    seahub.wsgi:application --preload

